/* =========================================
IDOMA-CONNECT
ASK AN ELDER
========================================= */

const ASK_ELDER_API = "http://localhost:8000";


/* =========================================
ELEMENTS
========================================= */

const askForm = document.getElementById("askForm");
const questionInput = document.getElementById("question");
const askButton = document.getElementById("askButton");
const askButtonText = document.getElementById("askButtonText");

const loadingState = document.getElementById("loadingState");
const errorState = document.getElementById("errorState");

const answerSection = document.getElementById("answerSection");
const answerContent = document.getElementById("answerContent");
const answerKind = document.getElementById("answerKind");

const sourcesSection = document.getElementById("sourcesSection");
const sourcesList = document.getElementById("sourcesList");

const backgroundSection = document.getElementById("backgroundSection");
const backgroundContent = document.getElementById("backgroundContent");

const webSourcesSection = document.getElementById("webSourcesSection");
const webSourcesList = document.getElementById("webSourcesList");

const noMatchState = document.getElementById("noMatchState");


/* =========================================
HELPERS
========================================= */

function show(element) {
    if (element) {
        element.classList.remove("hidden");
    }
}


function hide(element) {
    if (element) {
        element.classList.add("hidden");
    }
}


function setLoading(isLoading) {

    if (!askButton) {
        return;
    }

    askButton.disabled = isLoading;

    if (isLoading) {

        if (askButtonText) {
            askButtonText.textContent = "Searching...";
        }

        show(loadingState);

    } else {

        if (askButtonText) {
            askButtonText.textContent = "Ask an Elder";
        }

        hide(loadingState);
    }
}


/* =========================================
CLEAR PREVIOUS RESPONSE
========================================= */

function clearResponse() {

    hide(errorState);
    hide(answerSection);
    hide(noMatchState);
    hide(sourcesSection);
    hide(backgroundSection);
    hide(webSourcesSection);

    if (answerContent) {
        answerContent.innerHTML = "";
    }

    if (sourcesList) {
        sourcesList.innerHTML = "";
    }

    if (backgroundContent) {
        backgroundContent.innerHTML = "";
    }

    if (webSourcesList) {
        webSourcesList.innerHTML = "";
    }

    if (answerKind) {
        answerKind.textContent = "";
    }
}


/* =========================================
ERROR
========================================= */

function showError(message) {

    hide(answerSection);
    hide(noMatchState);

    if (!errorState) {
        return;
    }

    errorState.textContent = message;

    show(errorState);
}


/* =========================================
ANSWER KIND
========================================= */

function formatAnswerKind(kind) {

    const labels = {
        reference: "Reference",
        researched: "Researched",
        synthesised: "Synthesised",
        extractive: "Archive",
        no_match: "No match"
    };

    return labels[kind] || "Archive response";
}


/* =========================================
TEXT CLEANING
========================================= */

function cleanArchiveAnswer(answer) {

    if (!answer) {
        return "";
    }

    let text = String(answer);

    /*
    Remove the generic heading generated by the backend.
    The IDOMA-CONNECT interface provides its own heading.
    */

    text = text.replace(
        /^\s*##?\s*What the archive says\s*/i,
        ""
    );

    /*
    Remove the generic "ARCHIVE RESPONSE" heading if
    one ever comes back from the backend.
    */

    text = text.replace(
        /^\s*\*\*ARCHIVE RESPONSE\*\*\s*/i,
        ""
    );

    return text.trim();
}


/* =========================================
ARCHIVE ANSWER RENDERING
========================================= */

function renderAnswer(answer) {

    if (!answerContent) {
        return;
    }

    answerContent.innerHTML = "";

    const cleanedAnswer = cleanArchiveAnswer(answer);

    if (!cleanedAnswer) {

        const paragraph = document.createElement("p");

        paragraph.textContent =
            "No answer was returned from the archive.";

        answerContent.appendChild(paragraph);

        return;
    }


    /*
    Split the response into paragraphs while preserving
    the archive text safely.
    */

    const blocks = cleanedAnswer
        .split(/\n\s*\n/)
        .map((block) => block.trim())
        .filter(Boolean);


    blocks.forEach((block) => {

        /*
        Detect archive source entries such as:

        [1] Sample entry: ...
        */

        if (/^\[\d+\]\s/.test(block)) {

            const sourceBlock =
                document.createElement("div");

            sourceBlock.className =
                "answer-source-reference";

            const lines = block.split("\n");

            const firstLine = document.createElement("strong");

            firstLine.textContent =
                lines.shift().trim();

            sourceBlock.appendChild(firstLine);


            if (lines.length > 0) {

                const detail =
                    document.createElement("p");

                detail.textContent =
                    lines.join(" ").trim();

                sourceBlock.appendChild(detail);

            }

            answerContent.appendChild(sourceBlock);

            return;
        }


        /*
        Highlight the synthetic-data warning so users
        cannot mistake seed data for real testimony.
        */

        if (
            block.includes("[SAMPLE DATA") ||
            block.includes("synthetic placeholder")
        ) {

            const warning =
                document.createElement("div");

            warning.className =
                "archive-sample-warning";

            const title =
                document.createElement("strong");

            title.textContent =
                "Sample archive data";

            const text =
                document.createElement("p");

            text.textContent =
                block;

            warning.appendChild(title);
            warning.appendChild(text);

            answerContent.appendChild(warning);

            return;
        }


        /*
        Separate the provenance statement from the
        main archive response.
        */

        if (
            block.toLowerCase().startsWith(
                "quoted directly from the archive"
            )
        ) {

            const provenance =
                document.createElement("div");

            provenance.className =
                "archive-provenance";

            provenance.textContent =
                block;

            answerContent.appendChild(provenance);

            return;
        }


        const paragraph =
            document.createElement("p");

        paragraph.textContent = block;

        answerContent.appendChild(paragraph);

    });

}


/* =========================================
SOURCE HELPERS
========================================= */

function getSourceTitle(source) {

    return (
        source.title ||
        source.entry_title ||
        source.name ||
        "Idoma knowledge recording"
    );
}


function getSourceDescription(source) {

    return (
        source.summary ||
        source.description ||
        source.transcript_excerpt ||
        source.excerpt ||
        ""
    );
}


function getSourceAudio(source) {

    return (
        source.audio_url ||
        source.resolved_audio_url ||
        null
    );
}


function getSourceLocation(source) {

    return (
        source.location ||
        source.community ||
        source.place ||
        null
    );
}


/* =========================================
RESOLVE AUDIO URL
========================================= */

function resolveAudioURL(audioURL) {

    if (!audioURL) {
        return null;
    }

    /*
    If the backend already returned a complete URL,
    keep it unchanged.
    */

    if (
        audioURL.startsWith("http://") ||
        audioURL.startsWith("https://")
    ) {
        return audioURL;
    }

    /*
    Relative archive audio belongs to the FastAPI server,
    not the IDOMA-CONNECT frontend server.
    */

    if (audioURL.startsWith("/")) {
        return `${ASK_ELDER_API}${audioURL}`;
    }

    return `${ASK_ELDER_API}/${audioURL}`;
}


/* =========================================
SOURCE CARD
========================================= */

function createSourceCard(source, index) {

    const card =
        document.createElement("article");

    card.className = "source-card";


    const title =
        document.createElement("h4");

    title.textContent =
        getSourceTitle(source) ||
        `Archive source ${index + 1}`;

    card.appendChild(title);


    /*
    Contributor
    */

    if (source.contributor_name) {

        const contributor =
            document.createElement("p");

        contributor.className =
            "source-contributor";

        contributor.textContent =
            `Recorded by ${source.contributor_name}`;

        card.appendChild(contributor);
    }


    const description =
        getSourceDescription(source);

    if (description) {

        const paragraph =
            document.createElement("p");

        paragraph.textContent =
            description;

        card.appendChild(paragraph);
    }


    const meta =
        document.createElement("div");

    meta.className =
        "source-meta";


    const location =
        getSourceLocation(source);

    if (location) {

        const tag =
            document.createElement("span");

        tag.className =
            "source-tag";

        tag.textContent =
            location;

        meta.appendChild(tag);
    }


    if (source.entry_id || source.id) {

        const tag =
            document.createElement("span");

        tag.className =
            "source-tag";

        tag.textContent =
            `Archive #${source.entry_id || source.id}`;

        meta.appendChild(tag);
    }


    if (source.transcript_reviewed === true) {

        const tag =
            document.createElement("span");

        tag.className =
            "source-tag source-reviewed";

        tag.textContent =
            "Reviewed transcript";

        meta.appendChild(tag);

    } else if (source.transcript_reviewed === false) {

        const tag =
            document.createElement("span");

        tag.className =
            "source-tag source-unreviewed";

        tag.textContent =
            "Transcript not reviewed";

        meta.appendChild(tag);
    }


    if (meta.children.length > 0) {
        card.appendChild(meta);
    }


    /*
    Audio
    */

    const audioURL =
        resolveAudioURL(getSourceAudio(source));

    if (audioURL) {

        const audio =
            document.createElement("audio");

        audio.className =
            "source-audio";

        audio.controls = true;

        audio.preload = "none";

        audio.src = audioURL;

        card.appendChild(audio);
    }


    return card;
}


/* =========================================
ARCHIVE SOURCES
========================================= */

function renderSources(sources) {

    if (
        !sourcesList ||
        !Array.isArray(sources) ||
        sources.length === 0
    ) {

        hide(sourcesSection);

        return;
    }


    sourcesList.innerHTML = "";


    sources.forEach((source, index) => {

        const card =
            createSourceCard(source, index);

        sourcesList.appendChild(card);

    });


    show(sourcesSection);
}


/* =========================================
BACKGROUND RESEARCH
========================================= */

function renderBackground(background) {

    if (!backgroundSection || !backgroundContent) {
        return;
    }

    if (!background) {

        hide(backgroundSection);

        return;
    }


    backgroundContent.innerHTML = "";


    /*
    The research layer returns Markdown-like text.
    We deliberately render it as text rather than HTML.
    */

    const blocks = String(background)
        .split(/\n\s*\n/)
        .map((block) => block.trim())
        .filter(Boolean);


    blocks.forEach((block) => {

        /*
        Detect simple headings.
        */

        if (
            block.length < 100 &&
            (
                block.endsWith("Origin") ||
                block.endsWith("Alekwu") ||
                block.endsWith("Local craft") ||
                block.endsWith("Traditional religion") ||
                block.endsWith("Scholarly history") ||
                block.startsWith("Idoma people")
            )
        ) {

            const heading =
                document.createElement("h4");

            heading.textContent =
                block.replace(/\[W\d+\]/g, "").trim();

            backgroundContent.appendChild(heading);

            return;
        }


        const paragraph =
            document.createElement("p");

        paragraph.textContent =
            block;

        backgroundContent.appendChild(paragraph);

    });


    show(backgroundSection);
}


/* =========================================
WEB SOURCES
========================================= */

function renderWebSources(webSources) {

    if (
        !webSourcesSection ||
        !webSourcesList ||
        !Array.isArray(webSources) ||
        webSources.length === 0
    ) {

        hide(webSourcesSection);

        return;
    }


    webSourcesList.innerHTML = "";


    webSources.forEach((source) => {

        if (!source || !source.url) {
            return;
        }


        const item =
            document.createElement("li");

        item.className =
            "web-source-item";


        const link =
            document.createElement("a");

        link.href = source.url;

        link.target = "_blank";

        link.rel = "noopener noreferrer";

        link.textContent =
            source.title ||
            source.url;


        item.appendChild(link);

        webSourcesList.appendChild(item);

    });


    if (webSourcesList.children.length > 0) {
        show(webSourcesSection);
    }
}


/* =========================================
RESPONSE
========================================= */

function renderResponse(data) {

    clearResponse();


    const kind =
        data?.answer_kind ||
        data?.kind ||
        "extractive";


    if (kind === "no_match") {

        show(noMatchState);

        return;
    }


    if (answerKind) {

        answerKind.textContent =
            formatAnswerKind(kind);

    }


    renderAnswer(data?.answer);

    renderSources(data?.sources);

    renderBackground(data?.background);

    renderWebSources(data?.web_sources);


    show(answerSection);
}


/* =========================================
ASK API
========================================= */

async function askElder(question) {

    const response =
        await fetch(
            `${ASK_ELDER_API}/ask`,
            {
                method: "POST",

                headers: {
                    "Content-Type": "application/json"
                },

                body: JSON.stringify({
                    question: question
                })
            }
        );


    if (!response.ok) {

        let errorMessage =
            `Ask an Elder returned status ${response.status}.`;


        try {

            const errorData =
                await response.json();

            if (errorData?.detail) {
                errorMessage =
                    errorData.detail;
            }

        } catch (error) {
            /*
            Response was not JSON.
            Keep the HTTP status message.
            */
        }


        throw new Error(errorMessage);
    }


    return await response.json();
}


/* =========================================
FORM SUBMISSION
========================================= */

if (askForm) {

    askForm.addEventListener(
        "submit",
        async function (event) {

            event.preventDefault();


            const question =
                questionInput?.value.trim();


            if (!question) {

                showError(
                    "Please enter a question before asking."
                );

                return;
            }


            clearResponse();

            setLoading(true);


            try {

                const data =
                    await askElder(question);

                renderResponse(data);

            } catch (error) {

                console.error(
                    "Ask an Elder request failed:",
                    error
                );


                showError(
                    "We could not connect to the Ask an Elder archive. " +
                    "Please make sure the knowledge service is running."
                );

            } finally {

                setLoading(false);

            }

        }
    );
}
